service: ts-serverless-template

provider:
  name: aws
  runtime: nodejs10.x
  env: ${opt:env, self:provider.stage}
  # Use a shared deployment bucket
  # deploymentBucket:
  #   name: "some-bucket"
  logs:
    restApi: true
  tracing:
    lambda: true
    apiGateway: true
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}

functions:
  main:
    handler: dist/index.main
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: ${env:PORT, '4144'}
